version: '3.7' 
services: 
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    container_name: mysql
    volumes:
    - ./db/sql/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: avito
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 45
    depends_on:
      - db
    ports:
      - 8080:8080
